package com.athqyj.hqyj.Mapper.ym;

import com.athqyj.hqyj.entity.NvYibanqingkuang;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface WomenMapper{

   /* @Insert("insert  into `nv_yibanqingkuang`(`ID`,`isIll`,`anemia`,`hypertension`,`heartDisease`,`diabetes`,`epilepsy`,`thyroidDisease`,`chronicNephritis`,`swelling`,`nodule`,`hb`,`sexuallyInfect`,`psyDisorder`,`isIllOthers`,`isIllOthersBox`,`isBornIll`,`isBornIllBox`,`question`,`uterine`,`sterility`,`questionOthers`,`questionOthersBox`,`useMedicine`,`useMedicineBox`,`vaccinate`,`fengzhen`,`yigan`,`vaccinateOthers`,`vaccinateOthersBox`,`contracept`,`intrauterineDevice`,`subcutaneousImplants`,`oralContraceptive`,`condom`,`topicalContraceptives`,`naturalContracept`,`contraceptOthers`,`contraceptOthersBox`,`contraceptPeriod`,`contraceptStop`,`contraceptStopTime`,`firstTimeAge`,`lastTime`,`mensesRegular`,`mensPeriod`,`mensPeriodMax`,`mensCycle`,`mensCycleMax`,`mensQuanti`,`dysmenorrhea`,`breedHistory`,`pregNum`,`liveBirthNum`,`enouMonthNum`,`shortMonthNum`,`badPregnancyResult`,`deadBirth`,`deadBirthNum`,`abor`,`aborNum`,`induAbor`,`induAborNum`,`otherBadPregnancyResults`,`otherBadPregnancyResultsNum`,`sdChild`,`sdName`,`sdDetail`,`babyNum`,`childIll`,`childIllBox`,`intermarry`,`intermarryBox`,`intermarryF`,`intermarryFBox`,`diseaseHistoryF`,`thalassaemia`,`albinism`,`bloodSick`,`favism`,`congenitalHeartDisease`,`downSyndrome`,`diabetes1`,`dysgnosia`,`hearingDisorder`,`seeingDisorder`,`infantMortality`,`diseaseHistoryFOthers`,`diseaseHistoryFOthersBox`,`diseaseHistoryFRelationSh`,`meategg`,`hateVeg`,`rawMeat`,`smoking`,`smokingBox`,`secondHandSmoking`,`secondHandSmokingBox`,`drinking`,`drinkingBox`,`drug`,`drugBox`,`halitosis`,`gumBleeding`,`newDecoration`,`radial`,`highTemperature`,`noise`,`poisExpo`,`catdog`,`shake`,`leadHg`,`pesticide`,`poisExpoOthers`,`poisExpoOthersBox`,`pressure`,`tenseRelationship`,`economicPressure`,`pregnancyReady`,`otherPressure`,`doctorName`,`createServiceDate`,`DUpDate`,`DUPFlag`,`breedHistoryOther`,`breedHistoryOtherBox`,`lastTimes`,`isPreDisease`,`preDiseaseValueTNB`,`preDiseaseValueGXY`,`preDiseaseValueDanZhi`,`preDiseaseValueTsh`,`preDiseaseValuePinXue`,`preDiseaseValueOther`,`preDiseaseValueOtherbox`,`isCuttingPalace`,`cuttingPalaceDateTime`) values \n" +
            "(#{id},#{isIll},#{anemia},#{hypertension},#{heartDisease},#{diabetes},#{epilepsy},#{thyroidDisease},#{chronicNephritis},#{swelling}(10),#{nodule},#{hb},#{sexuallyInfect},#{psyDisorder},NULL,NULL,#{isBornIll},#{isBornIllBox},#{question},#{uterine}(20),#{sterility},NULL,NULL,#{useMedicine},#{useMedicineBox},#{vaccinate},#{fengzhen},#{yigan},#{vaccinateOthers},NULL(30),#{contracept},#{intrauterineDevice},#{subcutaneousImplants},#{oralContraceptive},#{condom},#{topicalContraceptives},#{naturalContracept},#{contraceptOthers},#{contraceptOthersBox},NULL(40),'0','2018-01-02','1',NULL,5,28,30,2,1,'1'(50),2,0,NULL,NULL,NULL,NULL,'0','0',NULL,0(60),NULL,0,NULL,0,NULL,0,NULL,NULL,NULL,'0(70)',NULL,'0',NULL,'0',NULL,'0','0','0','0','0(80)','0','0','0','0','0','0','0','0',NULL,NULL(90),'1','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',NULL(100),'0','0',NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL(110),NULL,NULL,NULL,NULL,NULL,NULL,#{pregnancyReady},NULL,#{doctorName},#{createServiceDate}(120),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL(130),NULL,NULL,NULL,NULL,NULL)")*/
   @Insert("insert  into `nv_yibanqingkuang`(`ID`,`isIll`,`anemia`,`hypertension`,`heartDisease`,`diabetes`,`epilepsy`,`thyroidDisease`,`chronicNephritis`,`swelling`,`nodule`,`hb`,`sexuallyInfect`,`psyDisorder`,`isIllOthers`,`isIllOthersBox`,`isBornIll`,`isBornIllBox`,`question`,`uterine`,`sterility`,`questionOthers`,`questionOthersBox`,`useMedicine`,`useMedicineBox`,`vaccinate`,`fengzhen`,`yigan`,`vaccinateOthers`,`vaccinateOthersBox`,`contracept`,`intrauterineDevice`,`subcutaneousImplants`,`oralContraceptive`,`condom`,`topicalContraceptives`,`naturalContracept`,`contraceptOthers`,`contraceptOthersBox`,`contraceptPeriod`,`contraceptStop`,`contraceptStopTime`,`firstTimeAge`,`lastTime`,`mensesRegular`,`mensPeriod`,`mensPeriodMax`,`mensCycle`,`mensCycleMax`,`mensQuanti`,`dysmenorrhea`,`breedHistory`,`pregNum`,`liveBirthNum`,`enouMonthNum`,`shortMonthNum`,`badPregnancyResult`,`deadBirth`,`deadBirthNum`,`abor`,`aborNum`,`induAbor`,`induAborNum`,`otherBadPregnancyResults`,`otherBadPregnancyResultsNum`,`sdChild`,`sdName`,`sdDetail`,`babyNum`,`childIll`,`childIllBox`,`intermarry`,`intermarryBox`,`intermarryF`,`intermarryFBox`,`diseaseHistoryF`,`thalassaemia`,`albinism`,`bloodSick`,`favism`,`congenitalHeartDisease`,`downSyndrome`,`diabetes1`,`dysgnosia`,`hearingDisorder`,`seeingDisorder`,`infantMortality`,`diseaseHistoryFOthers`,`diseaseHistoryFOthersBox`,`diseaseHistoryFRelationSh`,`meategg`,`hateVeg`,`rawMeat`,`smoking`,`smokingBox`,`secondHandSmoking`,`secondHandSmokingBox`,`drinking`,`drinkingBox`,`drug`,`drugBox`,`halitosis`,`gumBleeding`,`newDecoration`,`radial`,`highTemperature`,`noise`,`poisExpo`,`catdog`,`shake`,`leadHg`,`pesticide`,`poisExpoOthers`,`poisExpoOthersBox`,`pressure`,`tenseRelationship`,`economicPressure`,`pregnancyReady`,`otherPressure`,`doctorName`,`createServiceDate`,`DUpDate`,`DUPFlag`,`breedHistoryOther`,`breedHistoryOtherBox`,`lastTimes`,`isPreDisease`,`preDiseaseValueTNB`,`preDiseaseValueGXY`,`preDiseaseValueDanZhi`,`preDiseaseValueTsh`,`preDiseaseValuePinXue`,`preDiseaseValueOther`,`preDiseaseValueOtherbox`,`isCuttingPalace`,`cuttingPalaceDateTime`) values \n" +
           "(#{id},#{isIll},#{anemia},#{hypertension},#{heartDisease},#{diabetes},#{epilepsy},#{thyroidDisease},#{chronicNephritis},#{swelling},#{nodule},#{hb},#{sexuallyInfect},#{psyDisorder},NULL,NULL,#{isBornIll},#{isBornIllBox},#{question},#{uterine},#{sterility},NULL,NULL,#{useMedicine},#{useMedicineBox},#{vaccinate},#{fengzhen},#{yigan},#{vaccinateOthers},NULL,#{contracept},#{intrauterineDevice},#{subcutaneousImplants},#{oralContraceptive},#{condom},#{topicalContraceptives},#{naturalContracept},#{contraceptOthers},#{contraceptOthersBox},NULL,'0','2018-01-02','1',NULL,5,28,30,2,1,'1',2,0,NULL,NULL,NULL,NULL,'0','0',NULL,0,NULL,0,NULL,0,NULL,0,NULL,NULL,NULL,'0',NULL,'0',NULL,'0',NULL,'0','0','0','0','0','0','0','0','0','0','0','0','0',NULL,NULL,'1','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',NULL,'0','0',NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,#{pregnancyReady},NULL,#{doctorName},now(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)")
   public int addInfo(NvYibanqingkuang nvYibanqingkuang);


}